name: Test workflow
on:
  push:
    branches:
      - main # You can specify other branches if needed

permissions:
  id-token: write # Required to request the OIDC token
  contents: read # Optional, allows reading repository contents

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::741448947753:role/github # Replace with your IAM

role ARN
          role-session-name: test
          aws-region: us-east-1

      - name: AWS command
        run: |
          aws sts get-caller-identity
